name: Continuous Deployment 

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.0 

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform

      - name: Plan and Apply
        run: |
          terraform plan -input=false -out=tfplan
          terraform apply -auto-approve tfplan
        working-directory: ./terraform

      - name: Run Deployment Script
        run: |
          ls
        working-directory: ./Deployment

