name: Continuous Integrations
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout to main branch
        uses: actions/checkout@v2

      - name: Step 2 - Install Node.js and npm
        run: |
          sudo apt update
          sudo apt install -y nodejs
          sudo apt install -y npm
      - name : Step 3 - Run tests
        run: |
          npm install
          npm run test
      - name : Step 3 - Login to docker registry 
        uses: docker/login-action@v3
        with:
          username: rahulrwt
          password: dckr_pat_Pr1lr87VA-aqedaePDqFaUJUINA

      - name : Step 4 - Create docker image and push
        run: |
          docker build -t cooking-corner .
          docker tag cooking-corner rahulrwt/cooking-corner
          docker push rahulrwt/cooking-corner


