name: Github action for cooking corner
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout to main branch
        uses: actions/checkout@v2

      - name: Step 2 - Install Node.js and npm
        run: |
          sudo apt update
          sudo apt install -y nodejs
          sudo apt install -y npm
          npm run test
